name: copilot-exec
description: |
  Run AI-powered CLI with a rendered prompt template (wrapper around codex-exec).

  ⚠️  IMPLEMENTATION NOTE: This action now delegates to codex-exec (OpenAI Codex)
  instead of GitHub Copilot CLI to leverage official OpenAI tooling and reduce
  maintenance burden. The interface remains backward compatible.

  Features:
  - Automatic caching based on prompt content and model
  - Configurable timeout (default: 30 minutes)
  - Verbose logging for debugging
  - MCP (Model Context Protocol) configuration support
  - Conditional repository checkout (skips if already present)
  - Performance optimizations for faster workflow execution
author: "ralph@nyphon.de"
inputs:
  prompt-path:
    description: Path to the prompt template file
    required: true
  working-directory:
    description: Directory to run the command in
    required: false
    default: ""
  output-path:
    description: File path (relative to working-directory) to store output
    required: false
    default: copilot-output.txt
  extra-args:
    description: Additional arguments to append to the CLI invocation
    required: false
    default: ""
  additional-mcp-config:
    description: Optional MCP configuration JSON or @path to extend capabilities
    required: false
    default: ""
  allow-all-paths:
    description: Whether to allow CLI access to any file path
    required: false
    default: "true"
  model:
    description: Optional model identifier. If not provided or empty, defaults are used.
    required: false
    default: ""
  copilot-token:
    description: API token for AI service (mapped to codex-token internally). Defaults to github.token
    required: false
    default: ""
  timeout:
    description: Maximum time in minutes for CLI execution (default 30 minutes)
    required: false
    default: "30"
  verbose:
    description: Enable verbose logging for debugging (true/false, default false)
    required: false
    default: "false"
  force-response:
    description: Skip cache restoration to force fresh execution (true/false, default false). Useful for time-sensitive data analysis or debugging.
    required: false
    default: "false"

outputs:
  output-path:
    description: Absolute path to the CLI output file
    value: ${{ steps.exec.outputs.output-path }}

runs:
  using: composite
  steps:
    - name: Delegate to codex-exec
      id: exec
      uses: ./.github/actions/codex-exec
      with:
        prompt-path: ${{ inputs.prompt-path }}
        working-directory: ${{ inputs.working-directory }}
        output-path: ${{ inputs.output-path }}
        extra-args: ${{ inputs.extra-args }}
        additional-mcp-config: ${{ inputs.additional-mcp-config }}
        allow-all-paths: ${{ inputs.allow-all-paths }}
        model: ${{ inputs.model }}
        codex-token: ${{ inputs.copilot-token }}
        timeout: ${{ inputs.timeout }}
        verbose: ${{ inputs.verbose }}
        force-response: ${{ inputs.force-response }}
