enableImmutableInstalls: false

nodeLinker: node-modules

npmScopes:
  ralphschuler:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true

yarnPath: .yarn/releases/yarn-4.11.0.cjs
