name: copilot-ci-autofix-agent
description: |
  Specialized Copilot agent for CI failure resolution and automated fixes.

  Features:
  - Intelligent failure classification (lint, format, compilation, etc.)
  - Specialized fix strategies per failure type
  - Context-aware branch strategy (PR vs main vs feature)
  - Manual review escalation for complex issues
  - Single responsibility focused on CI fix operations
author: "ralph@nyphon.de"
inputs:
  copilot-token:
    description: Personal access token with Copilot Requests scope
    required: true
  repository:
    description: Repository name in owner/repo format
    required: false
    default: ${{ github.repository }}
  workflow-name:
    description: Name of the failed workflow (JSON-encoded)
    required: true
  run-id:
    description: Failed workflow run ID
    required: true
  run-url:
    description: Failed workflow run URL (JSON-encoded)
    required: true
  trigger-event:
    description: Event that triggered the workflow (JSON-encoded)
    required: true
  event-path:
    description: Path to the GitHub event payload file
    required: false
    default: ${{ github.event_path }}
  workspace:
    description: GitHub workspace directory
    required: false
    default: ${{ github.workspace }}
  verbose:
    description: Enable verbose logging for debugging
    required: false
    default: "true"
  timeout:
    description: Maximum time in minutes for Copilot CLI execution
    required: false
    default: "45"

outputs:
  output-path:
    description: Absolute path to the CI autofix output log file
    value: ${{ steps.autofix.outputs.output-path }}

runs:
  using: composite
  steps:
    - name: Run Copilot CI auto-fix
      id: autofix
      uses: ./.github/actions/copilot-exec
      env:
        REPO_NAME: ${{ inputs.repository }}
        WORKFLOW_NAME: ${{ inputs.workflow-name }}
        RUN_ID: ${{ inputs.run-id }}
        RUN_HTML_URL: ${{ inputs.run-url }}
        TRIGGER_EVENT: ${{ inputs.trigger-event }}
        EVENT_PATH: ${{ inputs.event-path }}
        WORKSPACE: ${{ inputs.workspace }}
      with:
        force-response: true
        copilot-token: ${{ inputs.copilot-token }}
        prompt-path: .github/copilot/prompts/ci-autofix
        output-path: reports/copilot/ci-autofix-${{ inputs.run-id }}.log
        timeout: ${{ inputs.timeout }}
        verbose: ${{ inputs.verbose }}
