name: Bug Report
description: Report a confirmed defect that requires fixing
title: "bug: "
labels: ["type/bug", "needs/regression-test", "state/pending"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide detailed information to help us reproduce and fix the issue.

        **Before submitting:** Search existing issues to avoid duplicates and check if this might be a feature request instead.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what's happening vs what should happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Navigate to...
        2. Execute command...
        3. Observe that...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe the actual behavior with error messages or screenshots
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - Runtime (creep behavior, memory, kernel)
        - Automation (CI/CD, workflows, GitHub actions)
        - Documentation (README, docs/, guides)
        - Monitoring (PTR stats, health checks)
        - Deployment (build process, Screeps server)
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - High (blocking, production outage)
        - Medium (degraded behavior)
        - Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Relevant environment information
      placeholder: |
        - Node.js version:
        - npm version: 
        - Screeps server: (MMO/PTR/Private)
        - Operating System:
        - Browser (if web-related):
      value: |
        - Node.js version:
        - npm version: 
        - Screeps server:
        - Operating System:
        - Browser (if web-related):

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Output
      description: Include relevant console output, error messages, or log files
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (related issues, workarounds, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched for existing issues and this is not a duplicate
          required: true
        - label: I have provided clear reproduction steps
          required: true
        - label: I have included relevant environment details
          required: true
        - label: This is a bug report, not a feature request
          required: true
