name: Documentation Improvement
description: Report missing, unclear, or outdated documentation
title: "docs: "
labels: ["documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear docs make the project more accessible to everyone.
        
        **Before submitting:** Check if there's already an issue for this documentation area.

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README.md (repository overview)
        - DOCS.md (developer guide)
        - AGENTS.md (automation guidelines)
        - docs/ directory (detailed guides)
        - Code comments/TSDoc
        - API documentation
        - Workflow documentation (.github/workflows/)
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Which specific file(s) or section(s) need improvement?
      placeholder: |
        File: README.md
        Section: "Getting Started"
        Lines: 25-40 (if applicable)
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What's wrong with the current documentation?
      options:
        - Missing (no docs for this topic)
        - Outdated (docs don't match current behavior)
        - Unclear (confusing or hard to understand)
        - Incomplete (missing important details)
        - Incorrect (factually wrong information)
        - Poor organization (hard to find or navigate)
    validations:
      required: true

  - type: textarea
    id: current_problem
    attributes:
      label: Current Problem
      description: What specific issues exist with the current documentation?
      placeholder: Describe what's missing, outdated, or confusing
    validations:
      required: true

  - type: textarea
    id: proposed_improvement
    attributes:
      label: Proposed Improvement
      description: How should the documentation be improved?
      placeholder: |
        - Add section explaining...
        - Update examples to show...
        - Clarify the explanation of...
        - Reorganize to make it easier to...
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this documentation improvement?
      options:
        - New contributors
        - Experienced developers
        - Repository maintainers
        - Screeps beginners
        - Automation users
        - All users
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Describe the user journey that this documentation would support
      placeholder: |
        As a [user type], I want to [goal] so that I can [benefit].
        When I [scenario], I expect the docs to help me [outcome].

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Provide examples of what good documentation looks like for this topic
      placeholder: |
        - Links to similar docs in other projects
        - Specific examples or code snippets
        - Screenshots of UI elements (if applicable)

  - type: checkboxes
    id: scope
    attributes:
      label: Improvement Scope
      description: What areas should this documentation improvement cover?
      options:
        - label: Add new content
        - label: Update existing content
        - label: Improve code examples
        - label: Add diagrams or screenshots
        - label: Improve navigation/organization
        - label: Fix grammar/spelling
        - label: Update links
        - label: Add cross-references

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this documentation improvement is complete?
      placeholder: |
        - [ ] Documentation clearly explains [concept]
        - [ ] Examples are working and up-to-date
        - [ ] New users can follow the guide successfully
        - [ ] Information is easy to find and navigate
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, related issues, or resources

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched for existing documentation issues
          required: true
        - label: I have clearly identified what needs improvement
          required: true
        - label: I have provided specific suggestions for improvement
          required: true
        - label: I have defined clear acceptance criteria
          required: true