name: Feature Request
description: Suggest a new feature or enhancement beyond bug fixes
title: "feat: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand your needs so we can build the right solution.
        
        **Before submitting:** Search existing issues to see if this has been requested before.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current pain point?
      placeholder: Describe the problem you're trying to solve or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this problem to be solved?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system would this affect?
      options:
        - Runtime (creep behavior, memory, kernel)
        - Automation (CI/CD, workflows, GitHub actions)
        - Documentation (README, docs/, guides)
        - Monitoring (PTR stats, health checks)
        - Deployment (build process, Screeps server)
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High (blocking current work)
        - Medium (would be helpful)
        - Low (nice to have)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches have you considered?
      placeholder: Describe alternative solutions or workarounds you've considered

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete and working?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. When [scenario], the system should [behavior]

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What areas of the codebase would this feature affect?
      placeholder: |
        - Runtime performance: 
        - Memory usage:
        - API compatibility:
        - Testing requirements:
        - Documentation needs:

  - type: checkboxes
    id: testing
    attributes:
      label: Testing Requirements
      description: What types of testing would this feature need?
      options:
        - label: Unit tests for core functionality
        - label: End-to-end tests for user workflows  
        - label: Performance/load testing
        - label: Regression tests to prevent future breaks
        - label: Integration tests with Screeps server

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, examples, or related issues

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched for existing issues and this is not a duplicate
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: I have provided concrete acceptance criteria
          required: true
        - label: This is a feature request, not a bug report
          required: true