name: copilot-triage-agent
description: |
  Specialized Copilot agent for GitHub issue triage and reformulation.

  Features:
  - Context-aware issue analysis with duplicate detection
  - Automatic reformulation of title and description
  - Intelligent label application based on content
  - Related issue linking and relationship management
  - Single responsibility focused on triage operations
author: "ralph@nyphon.de"
inputs:
  copilot-token:
    description: Personal access token with Copilot Requests scope
    required: true
  issue-number:
    description: GitHub issue number to triage
    required: true
  issue-title:
    description: Issue title (JSON-encoded)
    required: true
  issue-body:
    description: Issue body content (JSON-encoded)
    required: false
    default: ""
  issue-url:
    description: Issue HTML URL
    required: true
  issue-author:
    description: Issue author username (JSON-encoded)
    required: true
  repository:
    description: Repository name in owner/repo format
    required: false
    default: ${{ github.repository }}
  verbose:
    description: Enable verbose logging for debugging
    required: false
    default: "false"

outputs:
  output-path:
    description: Absolute path to the triage output log file
    value: ${{ steps.triage.outputs.output-path }}

runs:
  using: composite
  steps:
    - name: Run Copilot triage
      id: triage
      uses: ./.github/actions/copilot-exec
      env:
        REPO_NAME: ${{ inputs.repository }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        ISSUE_TITLE: ${{ inputs.issue-title }}
        ISSUE_BODY: ${{ inputs.issue-body }}
        ISSUE_HTML_URL: ${{ inputs.issue-url }}
        ISSUE_AUTHOR: ${{ inputs.issue-author }}
      with:
        force-response: true
        copilot-token: ${{ inputs.copilot-token }}
        prompt-path: .github/copilot/prompts/issue-triage
        output-path: reports/copilot/issue-triage-${{ inputs.issue-number }}.log
        verbose: ${{ inputs.verbose }}
