name: copilot-audit-agent
description: |
  Specialized Copilot agent for scheduled repository health checks and audits.

  Features:
  - Periodic repository health assessment
  - Automation and workflow quality evaluation
  - Strategic recommendations for improvements
  - Trend analysis and performance tracking
  - Single responsibility focused on audit operations
author: "ralph@nyphon.de"
inputs:
  copilot-token:
    description: API token for GitHub Copilot service (use secrets.COPILOT_TOKEN)
    required: true
  github-token:
    description: GitHub token for gh CLI authentication (use secrets.GITHUB_TOKEN)
    required: false
    default: ""
  repository:
    description: Repository name in owner/repo format
    required: false
    default: ${{ github.repository }}
  run-id:
    description: GitHub Actions run ID for tracking
    required: false
    default: ${{ github.run_id }}
  run-url:
    description: GitHub Actions run URL
    required: false
    default: ""
  verbose:
    description: Enable verbose logging for debugging
    required: false
    default: "false"
  timeout:
    description: Maximum time in minutes for Copilot CLI execution
    required: false
    default: "30"

outputs:
  output-path:
    description: Absolute path to the audit output log file
    value: ${{ steps.audit.outputs.output-path }}

runs:
  using: composite
  steps:
    - name: Run Copilot repository audit
      id: audit
      uses: ./.github/actions/copilot-exec
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        REPO_NAME: ${{ inputs.repository }}
        RUN_ID: ${{ inputs.run-id }}
        RUN_URL: ${{ inputs.run-url }}
      with:
        force-response: true
        copilot-token: ${{ inputs.copilot-token }}
        prompt-path: .github/copilot/prompts/repository-audit
        output-path: reports/copilot/repository-audit-${{ inputs.run-id }}.log
        verbose: ${{ inputs.verbose }}
        timeout: ${{ inputs.timeout }}
