/**
 * Regression test for versions.md file format requirements
 * 
 * Related to workflow run: 18703566323
 * Issue: npm run versions:update failing due to missing trailing newline
 * Root cause: versions.md file was missing required trailing newline
 */

import { readFileSync } from 'fs'
import { resolve } from 'path'
import { describe, it, expect } from 'vitest'

describe('versions.md format requirements', () => {
  it('should end with trailing newline to satisfy versions:update script', () => {
    const versionsPath = resolve(__dirname, '../../docs/changelog/versions.md')
    const content = readFileSync(versionsPath, 'utf-8')
    
    // File should end with newline
    expect(content).toMatch(/\n$/)
    
    // Should have the expected content structure
    expect(content).toMatch(/^# Release History/)
    expect(content).toContain('_This file is generated by `npm run versions:update`')
  })
})