name: "Setup Python 2"
description: "Installs Python 2.7.18 from official sources (builds on Linux, prebuilt on macOS)"
author: "ralph@nyphon.de"

runs:
  using: "composite"
  steps:
    - name: Install Python 2.7.18
      id: install
      shell: bash
      run: |
        set -euo pipefail
        echo "🐍 Installing Python 2.7.18..."

        ARCH="$(uname -m)"
        OS="$(uname -s)"
        INSTALL_DIR="/usr/local/python2"
        TMPDIR="$(mktemp -d)"
        PYTHON_VERSION="2.7.18"

        if [[ "$OS" == "Linux" ]]; then
          echo "🐧 Building Python $PYTHON_VERSION from source..."
          cd "$TMPDIR"
          curl -fsSL "https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz" -o python.tgz
          tar -xzf python.tgz
          cd "Python-$PYTHON_VERSION"

          # Configure and compile
          sudo mkdir -p "$INSTALL_DIR"
          ./configure --prefix="$INSTALL_DIR" --enable-optimizations
          make -j"$(nproc)"
          sudo make altinstall

          # Symlink for global use
          sudo ln -sf "$INSTALL_DIR/bin/python2.7" /usr/local/bin/python
          PYTHON_PATH="$INSTALL_DIR/bin/python2.7"

        elif [[ "$OS" == "Darwin" ]]; then
          echo "🍏 Installing prebuilt Python $PYTHON_VERSION for macOS..."
          cd "$TMPDIR"
          curl -fsSL "https://www.python.org/ftp/python/$PYTHON_VERSION/python-$PYTHON_VERSION-macosx10.9.pkg" -o python.pkg
          sudo installer -pkg python.pkg -target /

          PYTHON_PATH="$(command -v python2 || true)"
          [[ -z "$PYTHON_PATH" ]] && PYTHON_PATH="/usr/local/bin/python2"
          sudo ln -sf "$PYTHON_PATH" /usr/local/bin/python

        else
          echo "❌ Unsupported OS: $OS"
          exit 1
        fi

        echo "✅ Verifying installation..."
        python --version || (echo "⚠️ Python not found in PATH" && exit 1)

        echo "🎉 Installed Python 2.7.18 successfully!"
        echo "python-path=$PYTHON_PATH" >> $GITHUB_OUTPUT
