name: "Screeps AutoSpawner"
description: "Automatically checks spawn status and triggers respawn if needed after deployment"
inputs:
  screeps-token:
    description: "Screeps API token for authentication"
    required: true
  screeps-host:
    description: "Screeps server hostname"
    required: false
    default: "screeps.com"
  screeps-protocol:
    description: "Protocol (http or https)"
    required: false
    default: "https"
  screeps-port:
    description: "Screeps server port"
    required: false
    default: "443"
  screeps-path:
    description: "Screeps server path"
    required: false
    default: "/"
outputs:
  status:
    description: "Spawn status after check (normal, lost, empty, or spawned)"
    value: ${{ steps.autospawn.outputs.status }}
  action-taken:
    description: "Action taken by the autospawner (none, respawned)"
    value: ${{ steps.autospawn.outputs.action }}
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.1

    - name: Check spawn status and auto-respawn
      id: autospawn
      shell: bash
      env:
        SCREEPS_TOKEN: ${{ inputs.screeps-token }}
        SCREEPS_HOST: ${{ inputs.screeps-host }}
        SCREEPS_PROTOCOL: ${{ inputs.screeps-protocol }}
        SCREEPS_PORT: ${{ inputs.screeps-port }}
        SCREEPS_PATH: ${{ inputs.screeps-path }}
      run: |
        cd ${{ github.action_path }}/../../..
        bun run tsx packages/utilities/scripts/screeps-autospawn.ts
