name: copilot-dev-agent
description: |
  ⚠️ DEPRECATED: Use copilot-issue-agent with mode: resolve instead.

  Legacy Copilot agent for development workflow assistance.
  This action has been superseded by the unified copilot-issue-agent.

  Migration:
    OLD: uses: ./.github/actions/copilot-dev-agent
    NEW: uses: ./.github/actions/copilot-issue-agent
         with:
           mode: resolve

  See: .github/actions/copilot-issue-agent/README.md

  Features:
  - Context-aware code implementation and fixes
  - Dependency and sub-task validation
  - Incremental progress reporting and commit management
  - Automated testing and validation
author: "ralph@nyphon.de"
deprecated: true
inputs:
  copilot-token:
    description: Personal access token with Copilot Requests scope
    required: true
  issue-number:
    description: GitHub issue number to implement
    required: true
  issue-title:
    description: Issue title (JSON-encoded)
    required: true
  issue-body:
    description: Issue body content (JSON-encoded)
    required: false
    default: ""
  issue-url:
    description: Issue HTML URL
    required: true
  issue-author:
    description: Issue author username (JSON-encoded)
    required: true
  repository:
    description: Repository name in owner/repo format
    required: false
    default: ${{ github.repository }}
  verbose:
    description: Enable verbose logging for debugging
    required: false
    default: "false"
  timeout:
    description: Maximum time in minutes for Copilot CLI execution
    required: false
    default: "45"

outputs:
  output-path:
    description: Absolute path to the development output log file
    value: ${{ steps.develop.outputs.output-path }}

runs:
  using: composite
  steps:
    - name: Run Copilot development automation
      id: develop
      uses: ./.github/actions/codex-exec
      env:
        REPO_NAME: ${{ inputs.repository }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        ISSUE_TITLE: ${{ inputs.issue-title }}
        ISSUE_BODY: ${{ inputs.issue-body }}
        ISSUE_HTML_URL: ${{ inputs.issue-url }}
        ISSUE_AUTHOR: ${{ inputs.issue-author }}
      with:
        codex-token: ${{ inputs.copilot-token }}
        prompt-path: .github/copilot/prompts/todo-issue
        output-path: reports/copilot/todo-issue-${{ inputs.issue-number }}.log
        verbose: ${{ inputs.verbose }}
        timeout: ${{ inputs.timeout }}
