---
name: Copilot Spec-Kit

on:
  issues:
    types:
      - labeled
  issue_comment:
    types:
      - created

permissions:
  contents: read
  issues: write

jobs:
  generate-plan:
    if: |
      github.event_name == 'issues' &&
      github.event.action == 'labeled' &&
      github.event.label.name == 'speckit'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Generate implementation plan
        uses: ./.github/actions/copilot-exec
        env:
          REPO_NAME: "${{ github.repository }}"
          ISSUE_NUMBER: "${{ github.event.issue.number }}"
          ISSUE_TITLE: ${{ toJSON(github.event.issue.title) }}
          ISSUE_BODY: ${{ toJSON(github.event.issue.body || '') }}
          ISSUE_HTML_URL: ${{ toJSON(github.event.issue.html_url) }}
          ISSUE_AUTHOR: ${{ toJSON(github.event.issue.user.login) }}
        with:
          copilot-token: ${{ secrets.COPILOT_TOKEN }}
          prompt-path: .github/copilot/prompts/speckit-plan
          output-path: >-
            reports/copilot/speckit-plan-${{
            github.event.issue.number }}.log

  refine-plan:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.action == 'created' &&
      startsWith(github.event.comment.body, '@speckit')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Refine implementation plan
        uses: ./.github/actions/copilot-exec
        env:
          REPO_NAME: "${{ github.repository }}"
          ISSUE_NUMBER: "${{ github.event.issue.number }}"
          ISSUE_TITLE: ${{ toJSON(github.event.issue.title) }}
          ISSUE_HTML_URL: ${{ toJSON(github.event.issue.html_url) }}
          COMMENT_BODY: ${{ toJSON(github.event.comment.body) }}
          COMMENT_AUTHOR: ${{ toJSON(github.event.comment.user.login) }}
        with:
          copilot-token: ${{ secrets.COPILOT_TOKEN }}
          prompt-path: .github/copilot/prompts/speckit-refine
          output-path: >-
            reports/copilot/speckit-refine-${{
            github.event.issue.number }}-${{
            github.event.comment.id }}.log
