---
name: Daily Autonomous Bot Monitor

on:
  schedule:
    # Run daily at 06:00 UTC (optimal time for daily strategic analysis)
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  autonomous-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run autonomous strategic monitoring
        uses: ./.github/actions/copilot-exec
        env:
          REPO_NAME: "${{ github.repository }}"
          RUN_ID: "${{ github.run_id }}"
          RUN_URL: >-
            https://github.com/${{ github.repository }}/actions/runs/${{
            github.run_id }}
          SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
          SCREEPS_EMAIL: ${{ secrets.SCREEPS_EMAIL }}
          SCREEPS_PASSWORD: ${{ secrets.SCREEPS_PASSWORD }}
          SCREEPS_HOST: ${{ secrets.SCREEPS_HOST }}
          SCREEPS_SHARD: ${{ secrets.SCREEPS_SHARD }}
          SCREEPS_STATS_HOST: ${{ secrets.SCREEPS_STATS_HOST }}
          SCREEPS_STATS_API: ${{ secrets.SCREEPS_STATS_API }}
        with:
          copilot-token: ${{ secrets.COPILOT_TOKEN }}
          prompt-path: .github/copilot/prompts/autonomous-monitor
          output-path: >-
            reports/copilot/autonomous-monitor-${{ github.run_id }}.log
          additional-mcp-config: >-
            @.github/mcp/screeps-mcp.json
          timeout: "40"
          verbose: "true"

      - name: Upload monitoring report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autonomous-monitor-report-${{ github.run_id }}
          path: reports/copilot/autonomous-monitor-${{ github.run_id }}.log
          retention-days: 30
