---
# DEPRECATED: This monolithic workflow has been split into focused guard
# workflows (guard-lint.yml, guard-format.yml, etc.) for better granularity
# and parallel execution. This workflow is kept for backward compatibility.
name: Quality Gate (Deprecated)

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      SCREEPS_TEST_REALM: PTR
      SCREEPS_HOST: ptr.screeps.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1
      - name: Install dependencies
        run: bun install --no-optional
      - name: Cache build output
        id: cache-build
        uses: actions/cache@v4
        with:
          path: dist
          key: >-
            build-${{ runner.os }}-${{ hashFiles('src/**/*',
            'scripts/build.ts', 'tsconfig.json', 'bun.lock') }}
          restore-keys: |
            build-${{ runner.os }}-
      - name: Build AI
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: bun run build
      - name: YAML Lint
        run: yamllint .github/workflows/
      - name: Lint
        run: bun run lint
      - name: Format (check)
        run: bun run format:check
      - name: Validate version index
        run: |
          bun run versions:update
          if ! git diff --quiet docs/changelog/versions.json \
            docs/changelog/versions.md; then
            echo "::error::Release index is out of date. Run \
              'bun run versions:update' locally and commit the \
              changes." >&2
            git diff -- docs/changelog/versions.json \
              docs/changelog/versions.md
            exit 1
          fi
      - name: Unit tests
        run: bun run test:unit
      - name: End-to-end tests (PTR)
        run: bun run test:e2e
      - name: Regression tests
        run: bun run test:regression
      - name: Coverage
        run: bun run test:coverage
      - name: Publish evaluation report artifact
        if: success()
        run: |
          bun run analyze:system
          tar -czf reports.tar.gz reports || echo "no reports directory"
      - name: Upload report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: system-evaluation
          path: reports.tar.gz

      - name: Notify build failure
        if: failure()
        uses: ./.github/actions/send-push-notification
        with:
          push-token: ${{ secrets.PUSH_TOKEN }}
          title: "Quality Gate Failed"
          body: >-
            PR #${{ github.event.pull_request.number }} build failed
            - review required
          link: >-
            https://github.com/${{ github.repository }}/actions/runs/${{
            github.run_id }}
          priority: "4"
