name: Quality Gate

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      SCREEPS_TEST_REALM: PTR
      SCREEPS_HOST: ptr.screeps.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 2
        uses: ./.github/actions/setup-python2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies (with Python 2)
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Format (check)
        run: bun run format:check
      - name: Validate version index
        run: |
          bun run versions:update
          if ! git diff --quiet docs/changelog/versions.json docs/changelog/versions.md; then
            echo "::error::Release index is out of date. Run 'bun run versions:update' locally and commit the changes." >&2
            git diff -- docs/changelog/versions.json docs/changelog/versions.md
            exit 1
          fi
      - name: Unit tests
        run: bun run test:unit
      - name: End-to-end tests (PTR)
        run: bun run test:e2e
      - name: Regression tests
        run: bun run test:regression
      - name: Coverage
        run: bun run test:coverage
      - name: Publish evaluation report artifact
        if: success()
        run: |
          bun run analyze:system
          tar -czf reports.tar.gz reports || echo "no reports directory"
      - name: Upload report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: system-evaluation
          path: reports.tar.gz
