name: Screeps Stats Monitor

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run Copilot stats monitor
        uses: ./.github/actions/copilot-exec
        env:
          SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
          SCREEPS_STATS_TOKEN: ${{ secrets.SCREEPS_STATS_TOKEN }}
          SCREEPS_STATS_HOST: ${{ secrets.SCREEPS_STATS_HOST }}
          SCREEPS_STATS_API: ${{ secrets.SCREEPS_STATS_API }}
        with:
          copilot-token: ${{ secrets.COPILOT_TOKEN }}
          prompt-path: .github/copilot/prompts/stats-analysis
          output-path: reports/copilot/stats-analysis-${{ github.run_id }}.log
