name: Screeps Stats Monitor

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run Copilot stats monitor
        uses: ./.github/actions/copilot-exec
        env:
          SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
          SCREEPS_STATS_TOKEN: ${{ secrets.SCREEPS_STATS_TOKEN }}
          SCREEPS_STATS_HOST: ${{ secrets.SCREEPS_STATS_HOST }}
          SCREEPS_STATS_API: ${{ secrets.SCREEPS_STATS_API }}
          SCREEPS_EMAIL: ${{ secrets.SCREEPS_EMAIL }}
          SCREEPS_PASSWORD: ${{ secrets.SCREEPS_PASSWORD }}
          SCREEPS_HOST: ${{ secrets.SCREEPS_HOST }}
          SCREEPS_PORT: ${{ secrets.SCREEPS_PORT }}
          SCREEPS_PROTOCOL: ${{ secrets.SCREEPS_PROTOCOL }}
        with:
          copilot-token: ${{ secrets.COPILOT_TOKEN }}
          prompt-path: .github/copilot/prompts/stats-analysis
          output-path: reports/copilot/stats-analysis-${{ github.run_id }}.log

      - name: Check for critical PTR alerts
        if: always()
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          npx tsx scripts/check-ptr-alerts.ts
